backend/app/crawler/urls.py
from django.urls import path

from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers

from app.crawler import test_views

from .views import DocsView, PageViewSet, TaskViewSet

app_name = "crawler"

router = DefaultRouter()

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, base_name='tasks')
router.register(r'pages', PageViewSet, base_name='pages')
task_router = routers.NestedSimpleRouter(router, r'tasks', lookup='task')
task_router.register(r'pages', PageViewSet, base_name='pages')
nodes_router = routers.NestedSimpleRouter(task_router, r'pages', lookup='page')

urlpatterns = router.urls + task_router.urls + nodes_router.urls

urlpatterns += [path('docs/', DocsView.as_view(), name='docs'), ]
# Testing page

urlpatterns += [
    path('test/', test_views.home, name='home'),
    path('test/page_1/', test_views.page_1, name='page_1'),
    path('test/page_2/', test_views.page_2, name='page_2'),
    path('test/page_3/', test_views.page_3, name='page_3'),
    path('test/page_4/', test_views.page_4, name='page_4'),
]

backend/urls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = "v1"

urlpatterns = [
    path('api/v1/', include('urls.v1.urls'), name="v1"),
    path('api/v1/admin', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/urls/v1/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('app.crawler.urls', namespace='crawler'), name="crawler"),
]

backend/app/crawler/models/core.py
from django.db import models
from django.utils.timezone import now


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.updated_at = now()
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    class Meta:
        abstract = True

backend/app/crawler/models/page.py
from django.db import models

from app.crawler.search import PageIndex
from app.media.models import Image

from .core import TimestampedModel
from .task import Task


class Page(TimestampedModel):
    task = models.ForeignKey(Task, related_name='pages', on_delete=models.CASCADE)
    target_url = models.URLField(max_length=255, null=False, blank=False)
    error = models.BooleanField(default=False)

    text = models.TextField()
    images = models.ManyToManyField(Image, blank=True)

    done = models.BooleanField(default=False)

    class Meta:
        unique_together = ('task', 'target_url',)

    def indexing(self):
        obj = PageIndex(
            meta={'id': self.id},
            text=self.text
        )
        obj.save()
        return obj.to_dict(include_meta=True)

backend/app/crawler/models/task.py
from django.conf import settings
from django.db import models

from .core import TimestampedModel


class Task(TimestampedModel):
    GENERIC_PARSER = '0'
    PARSER_CHOICE = (
        (GENERIC_PARSER, 'GenericParser'),
    )

    GENERIC_CRAWLER = '0'
    CRAWLER_CHOICE = (
        (GENERIC_PARSER, 'GenericCrawler'),
    )

    LOCAL = '0'
    S3 = '1'
    STORAGE_CHOICE = (
        (LOCAL, 'local'),
        (S3, 's3'),
    )

    TEXT = '0'
    IMAGES = '1'
    TEXT_AND_IMAGES = '2'
    TYPE_CHOICE = (
        (TEXT, 'text'),
        (IMAGES, 'images'),
        (TEXT_AND_IMAGES, 'text and images')
    )

    depth = models.IntegerField(null=False, blank=False, default=1)

    parser = models.CharField(max_length=1, null=False, blank=False, default=0, choices=PARSER_CHOICE)
    crawler = models.CharField(max_length=1, null=False, blank=False, default=0, choices=CRAWLER_CHOICE)
    task_type = models.CharField(max_length=1, null=False, blank=False, default=2, choices=TYPE_CHOICE)

    target_url = models.URLField(max_length=255, null=False, blank=False)

    images_storage = models.CharField(max_length=1, null=False, blank=False, default=0, choices=STORAGE_CHOICE)
    images_max_size = models.IntegerField(default=settings.DEFAULT_MAX_SIZE)

    done = models.BooleanField(default=False)

    @property
    def parse_images(self):
        if self.task_type in (self.IMAGES, self.TEXT_AND_IMAGES):
            return True
        return False

    @property
    def parse_text(self):
        if self.task_type in (self.TEXT, self.TEXT_AND_IMAGES):
            return True
        return False

backend/app/media/models.py
from django.db import models


class Image(models.Model):
    S3 = '1'
    LOCAL = '0'
    BACKENDS = ((LOCAL, 'local'), (S3, 's3'),)

    storage = models.CharField(max_length=255, choices=BACKENDS, default=LOCAL)
    url = models.URLField(max_length=255, null=False, blank=False)
    filename = models.CharField(max_length=255, null=False, blank=False)
    path = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.url

backend/app/crawler/views.py
from django.views.generic import TemplateView

from rest_framework.mixins import CreateModelMixin
from rest_framework.viewsets import ReadOnlyModelViewSet

from .models.page import Page
from .models.task import Task
from .serializers import (
    CreateTaskSerializer,
    DetailedPageSerializer,
    DetailedTaskSerializer,
    PageSerializer,
    RetrieveTaskSerializer
)


class TaskViewSet(CreateModelMixin, ReadOnlyModelViewSet):
    serializer_class = RetrieveTaskSerializer
    queryset = Task.objects.all()

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return DetailedTaskSerializer
        if self.action == 'create':
            return CreateTaskSerializer
        return super().get_serializer_class()


class PageViewSet(ReadOnlyModelViewSet):
    serializer_class = PageSerializer
    queryset = Page.objects.all()

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return DetailedPageSerializer
        return super().get_serializer_class()

    def filter_queryset(self, queryset):
        task_pk = self.request.parser_context.get('kwargs').get('task_pk', None)
        if task_pk is not None:
            return super().filter_queryset(queryset).filter(task=task_pk)
        return super().filter_queryset(queryset)


class DocsView(TemplateView):
    template_name = 'docs.html'

backend/app/crawler/templates/base.html
<html>
<head>
    <title>Testing app</title>
</head>
<body>
<a href="{% url 'crawler:home' %}">home</a>
{% block content %}
{% endblock %}
</body>
</html>

backend/app/crawler/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'crawler:page_1' %}">page_1</a>
<img src="{% get_media_prefix %}1.png">
<img src="{% get_media_prefix %}2.png">
<p>
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
</p>
{% endblock %}

backend/app/crawler/templates/page_1.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'crawler:page_2' %}">page_2</a>
<a href="{% url 'crawler:page_3' %}">page_3</a>
<p>
    "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
    aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo
    enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui
    ratione voluptatem sequi nesciunt. "
</p>
{% endblock %}

backend/app/crawler/templates/page_2.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'crawler:page_4' %}">page_4</a>
<p>
    "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque
    corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa
    qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita
    distinctio."
</p>
{% endblock %}

backend/app/crawler/templates/page_3.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'crawler:page_2' %}">page_2</a>
<a href="{% url 'crawler:page_3' %}">page_3</a>
<p>
    "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
    adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
    voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
    aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil
    molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
</p>
{% endblock %}

backend/app/crawler/templates/page_4.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'crawler:page_1' %}">page_1</a>
<a href="{% url 'crawler:page_2' %}">page_2</a>
<a href="{% url 'crawler:page_3' %}">page_3</a>
<a href="{% url 'crawler:page_4' %}">page_4</a>
<img src="{% get_media_prefix %}3.png">
<p>
    "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime
    placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut
    officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non
    recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias
    consequatur aut perferendis doloribus asperiores repellat."
</p>
{% endblock %}